fix: fixing readme, launcher.py, etc
minibox24/easygamebot pull request #4
Opened 2021-03-08 03:40 UTC by decave27

2021-03-08 10:00 UTC, minibox24 commented on launcher.sh
> +python launcher.py
doesn't work on linux, do i need to put this in?

2021-03-08 10:00 UTC, minibox24 requested changes
refactor launcher.py -> src/launcher.py

2021-03-08 10:03 UTC, decave27 commented on launcher.sh
> +python launcher.py
You won't have to put it in.

2021-03-20 08:51 UTC, decave27 commented
> 
> 
> refactor launcher.py -> src/launcher.py

✅

2021-03-20 08:55 UTC, minibox24 requested changes
remove `launcher.sh`

2021-03-20 08:59 UTC, minibox24 approved these changes

2021-03-20 08:59 UTC, merged